version: "3.9"

services:
  backend:
    build: ./backend
    container_name: apitrain-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./data:/app/data
    env_file:
      - ./backend/.env

  frontend:
    build: ./frontend
    container_name: apitrain-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
